"""Regenerate the auto-generated number blocks in the agent-facing findings docs.

Findings (`docs/phase1.{1,2,3}-findings.md`) are read RAW by agents, so they must contain real
numbers (not `{{key}}`). To keep those numbers from being hand-mistyped or drifting from the
committed JSON, the metric-bearing blocks are GENERATED here from `_metrics.load()` and written
between `<!-- gen:ID -->` / `<!-- /gen:ID -->` markers in the target file. The template (with
`{{key}}`) lives in BLOCKS below; run this script to (re)write the rendered block.

Run:    ./.venv/bin/python tools/report/build_findings.py
Verify: run it, then `git diff --exit-code docs/phase1.1-findings.md` (no diff = in sync).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import _metrics  # noqa: E402

# (target file relative to ROOT, block id, template with {{key}} placeholders)
BLOCKS = [
    ("docs/phase1.1-findings.md", "gate_summary", """\
| Component | Equation | Gate | Result | Pass |
|---|---|---|---|---|
| M1 CIM tile | `dev_lat = Σ N-tiles 2·M·K·n/G_eff(n,K)` (quad-core 512×512, **GOP/s**) | 2D G_eff(N,K) native fit median≤10%, p95≤20% | median **{{cim.decode_median_pct}}%**, p95 **{{cim.decode_p95_pct}}%** | ✅ |
| M2 PCIe/DMA | `floor + bytes/BW` ({{mem.pcie_floor_us}}µs, {{mem.pcie_bw}} GB/s fixed) | sanity + boundary recorded | positive, monotonic | ✅ |
| M2 DRAM | analytic eff-BW (Ramulator2 → 1.3 single-stream / 2 contention) | measured ∈ 55–85% of measured-mem peak | **LPDDR4x {{mem.lpddr4x_eff}}/{{mem.lpddr4x_peak}} GB/s ({{mem.lpddr4x_eff_pct}}%)**; sim LPDDR5 33/51 | ✅ |
| M4 GPU (Mali) | `attn_bmm = 27.74 + 0.442·kv` µs (offload) | median≤10%, p95≤20% | median **{{gpu.attn_median_pct}}%**, p95 **{{gpu.attn_p95_pct}}%** | ✅ |
| M4 CPU (A76) | softmax `a + b·kv`; others constants | median≤10%, p95≤20% | median **{{cpu.softmax_median_pct}}%**, p95 **{{cpu.softmax_p95_pct}}%** | ✅ |
| M4 NPU | — | blocked on #13 | placeholder | ⏸ |
| M5 trace | deterministic (oracle) | 0 orphans, semantic covered | 4 models, 0 orphans | ✅ |
| M7 energy | spec (15 TOPS/W, pJ/bit, A76 W) | sanity + ±20% no-flip | memory-dominated, robust | ✅ |
| M3 / M6 | — | contract only (Phase 2) | tunables + gaps recorded | ✅ |
| **Recompose** | `tok_s = BW_eff/weight_bytes` (fit 1b/3b→8b) | 8B hold-out ≤25% | **{{recompose.err_8b_pct}}%** ({{recompose.pred_8b}} vs {{recompose.meas_8b}}) | ✅ |"""),
]


def render_block(template, metrics):
    """Return the rendered block body (markers added by the caller)."""
    return _metrics.substitute(template, metrics)


def apply(write=True):
    """Rewrite each block's marker region. Returns dict {file: changed_bool}."""
    metrics = _metrics.load()
    changed = {}
    for rel, bid, template in BLOCKS:
        p = ROOT / rel
        text = p.read_text()
        body = render_block(template, metrics)
        block = f"<!-- gen:{bid} (generated by tools/report/build_findings.py) -->\n{body}\n<!-- /gen:{bid} -->"
        pat = re.compile(rf"<!-- gen:{bid}[^>]*-->.*?<!-- /gen:{bid} -->", re.S)
        if not pat.search(text):
            raise SystemExit(f"markers <!-- gen:{bid} --> .. <!-- /gen:{bid} --> not found in {rel}")
        new = pat.sub(lambda _m: block, text)
        changed[rel] = new != text
        if write and new != text:
            p.write_text(new)
    return changed


if __name__ == "__main__":
    ch = apply(write=True)
    for rel, c in ch.items():
        print(f"{'updated' if c else 'in-sync'}: {rel}")
